name: Node.js Web App CI
on: push

jobs:
  lint_and_test:
    name: Lint and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.1
      - uses: actions/setup-node@v1.4.2
        with:
          node-version: 12.x
      - run: npm ci
      - run: npm run lint
      - run: npm test
  build:
    name: Docker Build
    needs: [lint_and_test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.1
      - run: docker build .
